
<div class="jumbotron">
  <h1><i class="fa fa-bar-chart" aria-hidden="true"></i> Modelado de datos</h1>
  <p></p>
</div>

In [36]:
# Metodos leer y guardar PICKLE
from pickle import load, dump

# Métodos para RL
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score,roc_curve
from sklearn.model_selection import StratifiedKFold

#Métodos MLFlow
import mlflow
import mlflow.sklearn

# Métodos pandas y numpy
from numpy import exp
from numpy import logspace
from numpy import random
from numpy import mean
from numpy import max
from numpy import arange
from pandas import DataFrame
from pandas import Series


# Métodos para Knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

### Cargar datos

In [18]:
# Load data (deserialize)
with open('Data/data_engi_v1.pickle', 'rb') as handle:
    df = load(handle)

In [19]:
df

Date  Location   MinTemp   MaxTemp  Rainfall  Evaporation  \
0     2009-01-01         4  0.691208  1.575298  0.135801     1.655518   
1     2009-01-02         4  0.769131  0.671504  0.135801     2.099110   
2     2009-01-04         4  0.924976  1.919600  0.135801     1.360617   
3     2009-01-05         4  1.314588  2.034368  0.135801     1.528352   
4     2009-01-06         4  1.673032  2.407362  0.135801     1.490750   
...          ...       ...       ...       ...       ...          ...   
56415 2017-06-20         6  0.909391  1.317071  0.135801    -1.318198   
56416 2017-06-21         6  1.205497  1.202303  0.135801    -0.178193   
56417 2017-06-22         6  1.127574  1.230995  0.135801    -2.311520   
56418 2017-06-23         6  0.940560  1.087536  0.135801    -1.096055   
56419 2017-06-24         6  1.049652  1.073190  0.135801    -2.311520   

       Sunshine  WindGustDir  WindGustSpeed  WindDir9am  ...   Temp9am  \
0      1.214537           11       0.534126           1  ...  1.278186   
1      1.400800            8      -0.290764          10  ...  0.318980   
2      0.762183            5       0.384146           5  ...  1.597921   
3      1.187928           14      -0.740704          14  ...  1.658823   
4      0.176784           14      -0.440744           7  ...  2.343970   
...         ...          ...            ...         ...  ...       ...   
56415  0.868619            1      -0.440744           9  ...  0.958451   
56416  0.230002            0      -0.290764           9  ...  1.004127   
56417  0.868619            0      -0.590724           0  ...  1.004127   
56418  0.762183            2      -1.115654           9  ...  1.004127   
56419  0.788792            1      -0.815694           1  ...  1.095480   

        Temp3pm  RainToday  RainTomorrow  month  day     month_sin  month_cos  \
0      1.563621          0             0      1    1  5.000000e-01   0.866025   
1      0.627467          0             0      1    2  5.000000e-01   0.866025   
2      1.783032          0             0      1    4  5.000000e-01   0.866025   
3      1.885424          0             0      1    5  5.000000e-01   0.866025   
4      2.177972          0             0      1    6  5.000000e-01   0.866025   
...         ...        ...           ...    ...  ...           ...        ...   
56415  1.402719          0             0      6   20  1.224647e-16  -1.000000   
56416  1.358837          0             0      6   21  1.224647e-16  -1.000000   
56417  1.373465          0             0      6   22  1.224647e-16  -1.000000   
56418  0.949270          0             0      6   23  1.224647e-16  -1.000000   
56419  1.212563          0             0      6   24  1.224647e-16  -1.000000   

        day_sin   day_cos  
0      0.017213  0.999852  
1      0.034422  0.999407  
2      0.068802  0.997630  
3      0.085965  0.996298  
4      0.103102  0.994671  
...         ...       ...  
56415  0.337523  0.941317  
56416  0.353676  0.935368  
56417  0.369725  0.929141  
56418  0.385663  0.922640  
56419  0.401488  0.915864  

[56420 rows x 29 columns]

### Eliminar variables superfluas

In [20]:
del df['month']
del df['day']
del df['Date']
del df['day_sin']
del df['day_cos']

## Label

In [21]:
label = 'RainTomorrow'

In [22]:
Y = df[label]

del df[label]

## Features

In [23]:

X= df.values

In [24]:
len(X[0])

23

## Scaler

In [25]:
from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#scaler.fit(X)
#X = scaler.transform(X)

# Modeling

## Regresión logística


Debido a que las biliotecas de Sklearn no cuenta con la opcón de vsualizar los `p-values` y los coeficientes de la regresión en forma de tabla como lo hace la bilioteca `statsmodels` iniciaremos con un análisis utilizando dicha biblioteca

In [26]:
import statsmodels.api as sm
logit_model=sm.Logit(Y,X.astype(float))
result=logit_model.fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.357605
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:           RainTomorrow   No. Observations:                56420
Model:                          Logit   Df Residuals:                    56397
Method:                           MLE   Df Model:                           22
Date:                Thu, 05 Aug 2021   Pseudo R-squ.:                  0.3217
Time:                        11:53:55   Log-Likelihood:                -20176.
converged:                       True   LL-Null:                       -29747.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0632      0.002    -41.569      0.000      -0.066      -0.060
x2            -0.2399      0.

Podemos obervar que existen variables como `x5,x15,x20` y `x23` que no aportan información util al modelado y debería ser eliminadas. Es decir no son significativas por tener valores `p` mayores a 0.05

Los coeficientes de la regresión sólo muetras si cada variable suma o resta a la probabilidad de que llueva el dia de mañana. Para saber el peso que aporta cada variable o poder predictivo analizaramos los `odds ratios`

In [40]:
params = result.params
conf = result.conf_int()
conf['Odds Ratio'] = params
conf.columns = ['5%', '95%', 'Odds Ratio']
print(exp(conf))

           5%       95%  Odds Ratio
x1   0.936006  0.941597    0.938797
x2   0.719546  0.860200    0.786736
x3   1.051033  1.448291    1.233775
x4   1.037972  1.085473    1.061457
x5   0.965022  1.018807    0.991550
x6   0.547019  0.597726    0.571811
x7   0.980970  0.995083    0.988001
x8   2.195937  2.383347    2.287724
x9   0.924907  0.936109    0.930491
x10  0.942142  0.955368    0.948732
x11  0.825584  0.882749    0.853688
x12  0.811042  0.871418    0.840688
x13  1.045273  1.165082    1.103553
x14  2.902487  3.305032    3.097227
x15  0.876867  1.101752    0.982899
x16  0.596965  0.747513    0.668011
x17  0.887877  0.960872    0.923653
x18  1.220621  1.321619    1.270117
x19  0.784276  1.028842    0.898274
x20  0.877779  1.255300    1.049703
x21  1.293909  1.465309    1.376945
x22  0.902251  0.979737    0.940197
x23  0.963830  1.057212    1.009442


- Podemos vizualizar los invervalos de confianza ( los cuales su discución queda fuera del alcance debido al  tiempo) y los `odds ratio`.
- Los cuales nos dicen que la variable `x14` y `x8` son las de mayor aporte a la predicción positiva (que llueva) y es una propabilidad de 3 a 1 y de 2.2 a 1 respectivamente.

- Las los `odds ratios` con valores inferiores a .7 corresponden a las variable `x16` y `x6`, los cuales restan probabilidad a la premisa de que llovera mañana 

- El resto de valores de los `odds ratios` estan cercanos a 1 , lo cual no indica que el incremento/decremento en el valor de dichas variables incrementa/resta la propabilidad de que llueva mañana en una escala 1:1

Ahora entrenaremos un modelo y mediremos su rendimiento con la métrica accuracy y ROC. Se utilizara la biblioteca MLFlow para la administración de resultados.

### Definir los parámetros de búsqueda

In [53]:
def Find_Optimal_Cutoff(target, predicted):
    """
    Encuentre el punto de corte de probabilidad óptimo para un modelo de clasificación relacionado con la tasa de eventos

     Input:
   
         target: 
                 Matriz con las verdaderas etiquetas de clase, donde las filas son observaciones

         predicted: 
                 Matriz con datos predichos, donde las filas son observaciones

    Output :
                
        list type: con valor óptimo de corte
    """
    
    fpr, tpr, threshold = roc_curve(target, predicted)
    i = arange(len(tpr)) 
    roc = DataFrame({'tf' : Series(tpr-(1-fpr), index=i), 'threshold' : Series(threshold, index=i)})
    roc_t = roc.iloc[(roc.tf-0).abs().argsort()[:1]]

    return list(roc_t['threshold']) 

In [30]:
seed = 9
random.seed(seed)
num_folds = 5

#Hiperparámetros
anomaly_weights = [1,2,4, 5, 7, 10, 15]
penalty = ['l1', 'l2', 'elasticnet']
C = logspace(-3,3,7)


# define 10-fold cross validation test harness
kfold = StratifiedKFold(n_splits= 10, shuffle=True, random_state=seed)
logs = []

sólo se hara un búsqueda para los pesos óptimos de las clases, debido al problema de clases desvalanceadas, los demás hiperparámetros se dejan para un segundo sprint por falta de tiempo ya que los datos son de alta dimensión y con muestras arriba de 50 mil

In [32]:
mlflow.set_experiment("sklearn_RL_02")


for f in range(len(anomaly_weights)): #Búsqueda del peso de las clases 

    fold = 1
    accuracies = []
    auc_scores= []



    for train_index, test_index in kfold.split(X, Y):

        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = Y[train_index], Y[test_index]

        with mlflow.start_run():

            weight = anomaly_weights[f]
            mlflow.log_param("anomaly_weight", weight)
            class_weights= {
                0: 1,
                1: weight
                            }
            #-------------------------------------------------------------------<definir modelo>
            #definir modelos con los parámetros
            sk_model = LogisticRegression(
                                    random_state=None,
                                    max_iter=400,
                                    solver='newton-cg',
                                    class_weight=class_weights
                                            )
            #-------------------------------------------------------------------<entrenar modelo>
            #Entrenar el modelo
            sk_model.fit(X_train, y_train)

            #Separador 
            for h in range(40): print('-', end="")
            #------------------------------------------------

            print("fold: ",fold)
            print("Anomaly Weight: ", weight)

            #--------------------------------------------------------------------<Score train>
            #Obtner métrica accuracy con el train
            train_acc = sk_model.score(X_train, y_train)
            #Guardar métrica accuracy
            mlflow.log_metric("train_acc", train_acc)

            
            #--------------------------------------------------------------------<Score test>
            #Obtner métrica accuracy con el test
            eval_acc = sk_model.score(X_test, y_test)
            #Guardar métrica accuracy con el test
            mlflow.log_metric("eval_acc", eval_acc)

            #--------------------------------------------------------------------< Buscar el threshold óptimo>
            #obtener la probabilidad
            preds = sk_model.predict(X_test)

            
            threshold = Find_Optimal_Cutoff(y_test, preds)
            print("threshold: ", threshold[0])
            #cv_thresholds.extend(threshold)
            mlflow.log_metric("threshold", threshold[0])

            print("Aplicar el threshold correcto ...")
    
            y_pred = (sk_model.predict_proba(X_test)[:,1] > threshold[0]).astype(bool) # set threshold as 0.3
 
        
            acc = accuracy_score(y_test, preds)
            mlflow.log_metric("threshold_eval_acc", acc)
            
            #--------------------------------------------------------------------<Score con el threshold óptimo>
            
            cm = confusion_matrix(y_test, preds)
            print ("Confusion Matrix")
            print (cm)
            
            
            #---------------------------------------------------------------------<Obtener roc con el threshold óptimo>
            #Obtner la ROC
            try:
                auc_score = roc_auc_score(y_test,  sk_model.predict(X_test))
            except:
                auc_score = -1

                
            #----------------------------------------------------------------------<almacenar resultados>
            #Guardar el valor de ROC
            mlflow.log_metric("auc_score", auc_score)

            print("AUC: {}\neval_acc: {}".format(auc_score, eval_acc))

            #Agregar el valor del accuracy y la roc en la lista
            accuracies.append(eval_acc)
            auc_scores.append(auc_score)

            #Almacenar en un sólo objeto el modelo , el test , las etiquetas del test y la probabilidades (predicts)
            log = [sk_model, X_test, y_test, preds]
            #Agregar a la lista
            logs.append(log)

            #Almacenar del modelo con el peso de clases  y el fold correspondiente
            mlflow.sklearn.log_model(sk_model, f"anom_weight_{weight}_fold_{fold}")

            fold = fold + 1

            mlflow.end_run()

    print("\nAverages::::::::::::::::::::::::::::::::::::::::::::::::::::::::::. ")
    print("Accuracy: ", mean(accuracies))
    print("AUC: ", mean(auc_scores))
    print("Best::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::. ")
    print("Accuracy: ", max(accuracies))
    print("AUC: ", max(auc_scores))
    print("\n\n\n\n\n")

INFO: 'sklearn_RL_02' does not exist. Creating a new experiment
----------------------------------------fold:  1
Anomaly Weight:  1
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[4150  250]
 [ 553  690]]
AUC: 0.7491452131938857
eval_acc: 0.8576998050682261
----------------------------------------fold:  2
Anomaly Weight:  1
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[4157  243]
 [ 557  686]]
AUC: 0.7483316572807723
eval_acc: 0.8582314371788056
----------------------------------------fold:  3
Anomaly Weight:  1
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[4164  236]
 [ 586  657]]
AUC: 0.7374617860016092
eval_acc: 0.8543328017012227
----------------------------------------fold:  4
Anomaly Weight:  1
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[4144  255]
 [ 585  658]]
AUC: 0.7356983604662582
eval_acc: 0.8511166253101737
----------------------------------------fold:  5
Anomaly Weight:  1
threshold:  1
Ap

C:\Users\mcssa\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:314: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\mcssa\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')


----------------------------------------fold:  6
Anomaly Weight:  5
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[3306 1093]
 [ 199 1044]]
AUC: 0.7957189495089299
eval_acc: 0.7710031903580291
----------------------------------------fold:  7
Anomaly Weight:  5
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[3350 1049]
 [ 156 1087]]
AUC: 0.8180169485604953
eval_acc: 0.7864232541651897
----------------------------------------fold:  8
Anomaly Weight:  5
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[3363 1036]
 [ 199 1043]]
AUC: 0.8021332435749745
eval_acc: 0.7810671866690303
----------------------------------------fold:  9
Anomaly Weight:  5
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[3289 1110]
 [ 199 1043]]
AUC: 0.793722241074406
eval_acc: 0.7679489452224783
----------------------------------------fold:  10
Anomaly Weight:  5
threshold:  1
Aplicar el threshold correcto ...
Confusion Matrix
[[3248 1151]
 [

Podemos ver los resultados de MLFlow si ejecutamos en la terminal:



 _mlflow ui -p 1234_
 

## k NN

Experiementaremos con un algortimos basados en vecindades

In [52]:
#define the model and parameters
knn = KNeighborsClassifier()

parameters = {'n_neighbors':[1,3,5,7,9,11],
              #'leaf_size':[1,3,5],
              'metric':['euclidean','manhattan'],
              'weights':['uniform','distance'],
              #'algorithm':['auto', 'kd_tree'],
              'n_jobs':[-1]
             }

#Fit the model
model = GridSearchCV(knn, param_grid=parameters, cv=3)
model.fit(X,Y)



GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid={'metric': ['euclidean', 'manhattan'], 'n_jobs': [-1],
                         'n_neighbors': [1, 3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

Los resultados de la búsqueda son :

In [47]:
model.best_params_

{'metric': 'manhattan', 'n_jobs': -1, 'n_neighbors': 7, 'weights': 'distance'}

In [48]:
model.best_score_ 

0.8031017369727047

Con `k-NN` se esperaban resultados similares a `RL`. La lógica incial es que k-NN calcula un conjunto de pesos locales (sus k vecinos) y va de acorde a la premisa de que `sí` lloverá mañana tomando en cuenta las características del clima de hoy (y posible días anteriore) son condiciones mas locales que generales.
El modelo refuta esta idea

Veamos como se comporta las métricas restantes (matriz de confusión y ROC ) utilizando validación cruzada con los mejores hiperparámetros obtenidos en la búsqueda de malla

In [50]:
# Fuera del alcance por falta de tiempo